// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxMVlt56J__vxXovSoW4v9UJ-h6kDPP2w',
    appId: '1:397223061547:web:190941b71dd10fb5b5e26e',
    messagingSenderId: '397223061547',
    projectId: 'project-18aed',
    authDomain: 'project-18aed.firebaseapp.com',
    storageBucket: 'project-18aed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM-QMnhlRzq9r6fUrolgp4ORPkOIbBMlo',
    appId: '1:397223061547:android:6ba3b82664bb3426b5e26e',
    messagingSenderId: '397223061547',
    projectId: 'project-18aed',
    storageBucket: 'project-18aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNhivS6W2ksaiGGUlN3Qf3ayE9qR-DN44',
    appId: '1:397223061547:ios:6a1e2cb3cbaa6f4fb5e26e',
    messagingSenderId: '397223061547',
    projectId: 'project-18aed',
    storageBucket: 'project-18aed.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNhivS6W2ksaiGGUlN3Qf3ayE9qR-DN44',
    appId: '1:397223061547:ios:6a1e2cb3cbaa6f4fb5e26e',
    messagingSenderId: '397223061547',
    projectId: 'project-18aed',
    storageBucket: 'project-18aed.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxMVlt56J__vxXovSoW4v9UJ-h6kDPP2w',
    appId: '1:397223061547:web:c0b1acb2524942adb5e26e',
    messagingSenderId: '397223061547',
    projectId: 'project-18aed',
    authDomain: 'project-18aed.firebaseapp.com',
    storageBucket: 'project-18aed.appspot.com',
  );
}
